name: flutter_sodium
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.firstfloorsoftware.fluttersodium
    pluginClass: FlutterSodiumPlugin
