name: flutter_sodium
description: Flutter bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.0.9
author: First Floor Software <info@firstfloorsoftware.com>
homepage: https://github.com/firstfloorsoftware/flutter_sodium

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
